<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>scv_testbed</name>
  <version>0.1.0</version>
  <description>시험 스크립트, 가짜 데이터 도구, 기록 데이터 재생</description>
  <maintainer email="tnduaehowl37@gmail.com">doyoon-kim</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>scv_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
